import type { Guitar } from '@/types';

export const GUITAR_CATALOG: Guitar[] = [
  {
    id: 'g1',
    createdAt: new Date('2024-01-15'),
    name: 'Americana Dreadnought',
    brand: 'Strum & Scale',
    category: 'acoustic',
    price: 1299,
    imageSlot: 'guitar-1',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    bodyWood: 'Sitka Spruce / Mahogany',
    neckWood: 'Mahogany',
    fretboard: 'Rosewood',
    pickups: null,
    hardware: 'Chrome Tuners',
    finish: 'Natural Gloss',
    scaleLength: '25.4"',
    nutWidth: '1-11/16"',
    numberOfFrets: 20,
    inStock: true,
    featured: true,
    badge: 'Best Seller',
  },
  {
    id: 'g2',
    createdAt: new Date('2024-02-10'),
    name: 'Coronado Archtop',
    brand: 'Strum & Scale',
    category: 'electric',
    price: 2499,
    imageSlot: 'guitar-2',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    bodyWood: 'Laminate Maple',
    neckWood: 'Maple',
    fretboard: 'Ebony',
    pickups: 'Dual Humbuckers',
    hardware: 'Gold Tune-o-matic',
    finish: 'Vintage Sunburst',
    scaleLength: '24.75"',
    nutWidth: '1-11/16"',
    numberOfFrets: 22,
    inStock: true,
    featured: true,
    badge: 'Staff Pick',
  },
  {
    id: 'g3',
    createdAt: new Date('2024-03-05'),
    name: 'Obsidian Solid Body',
    brand: 'Strum & Scale',
    category: 'electric',
    price: 1899,
    imageSlot: 'guitar-3',
    videoUrl: null,
    bodyWood: 'Alder',
    neckWood: 'Maple',
    fretboard: 'Pau Ferro',
    pickups: 'HSS Configuration',
    hardware: 'Black Hardtail Bridge',
    finish: 'Gloss Jet Black',
    scaleLength: '25.5"',
    nutWidth: '1-5/8"',
    numberOfFrets: 22,
    inStock: true,
    featured: false,
    badge: 'New Arrival',
  },
  {
    id: 'g4',
    createdAt: new Date('2024-01-28'),
    name: 'Granada Classical',
    brand: 'Strum & Scale',
    category: 'classical',
    price: 1650,
    imageSlot: 'guitar-4',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    bodyWood: 'Cedar / Rosewood',
    neckWood: 'Cedar',
    fretboard: 'Ebony',
    pickups: null,
    hardware: 'Gold Tuning Machines',
    finish: 'Natural Satin',
    scaleLength: '25.6"',
    nutWidth: '2"',
    numberOfFrets: 19,
    inStock: false,
    featured: false,
    badge: 'Limited',
  },
  {
    id: 'g5',
    createdAt: new Date('2024-04-12'),
    name: 'Thunderline Bass',
    brand: 'Strum & Scale',
    category: 'bass',
    price: 2199,
    imageSlot: 'guitar-5',
    videoUrl: null,
    bodyWood: 'Swamp Ash',
    neckWood: 'Maple',
    fretboard: 'Rosewood',
    pickups: 'PJ Configuration',
    hardware: 'Black Hipshot Bridge',
    finish: 'Tobacco Burst',
    scaleLength: '34"',
    nutWidth: '1-5/8"',
    numberOfFrets: 24,
    inStock: true,
    featured: false,
    badge: null,
  },
  {
    id: 'g6',
    createdAt: new Date('2024-05-01'),
    name: 'Heritage Rosewood',
    brand: 'Strum & Scale',
    category: 'acoustic',
    price: 3299,
    imageSlot: 'guitar-6',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    bodyWood: 'Indian Rosewood / Engelmann Spruce',
    neckWood: 'Mahogany',
    fretboard: 'Ebony',
    pickups: null,
    hardware: 'Gold Waverly Tuners',
    finish: 'Aged Gloss Burst',
    scaleLength: '25.4"',
    nutWidth: '1-3/4"',
    numberOfFrets: 20,
    inStock: true,
    featured: true,
    badge: null,
  },
];

export const IMAGE_MAP: Record<string, string> = {
  'guitar-1': 'https://images.pexels.com/photos/12709726/pexels-photo-12709726.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'guitar-2': 'https://images.pexels.com/photos/8419956/pexels-photo-8419956.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'guitar-3': 'https://images.pexels.com/photos/31092490/pexels-photo-31092490.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'guitar-4': 'https://images.pexels.com/photos/31159671/pexels-photo-31159671.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'guitar-5': 'https://images.pexels.com/photos/37173828/pexels-photo-37173828.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'guitar-6': 'https://images.pexels.com/photos/9057628/pexels-photo-9057628.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'hero': 'https://images.pexels.com/photos/631869/pexels-photo-631869.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  'demo-1': 'https://images.pexels.com/photos/1428511/pexels-photo-1428511.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'demo-2': 'https://images.pexels.com/photos/8024692/pexels-photo-8024692.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'demo-3': 'https://images.pexels.com/photos/8197263/pexels-photo-8197263.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'about-workshop': 'https://images.pexels.com/photos/5059651/pexels-photo-5059651.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
};
